# Generated by Django 5.1.2 on 2024-10-25 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAsClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "counterparty",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="erp.counterparty",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
