# Generated by Django 5.1.2 on 2024-11-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Client profile', 'verbose_name_plural': 'Client profiles'},
        ),
    ]
