# Generated by Django 5.1.2 on 2024-11-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientprofile_options'),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='erp.counterparty'),
        ),
    ]
