version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./docker-db.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gasification

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gasification-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A services.celery_app worker --loglevel=info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - rabbitmq

  flower:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: celery_flower
    command: celery -A services.celery_app flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    env_file:
      - ./.env

volumes:
  postgres_data: