# Generated by Django 5.1.2 on 2025-01-17 08:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionobject",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="constructionobject",
            name="work_packages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SmallIntegerField(
                    choices=[
                        (1, "ГСН (газопровод-ввод)"),
                        (2, "ГСН (участок газопровода)"),
                        (3, "ГСВ"),
                    ]
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
