# Generated by Django 5.1.2 on 2024-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='on_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
