# Generated by Django 5.1.2 on 2024-12-12 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderconfig",
            name="time_end",
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AddField(
            model_name="orderconfig",
            name="time_start",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
