# Generated by Django 5.1.2 on 2024-12-23 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderconfig_time_end_orderconfig_time_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderconfig",
            name="max_date",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="orderconfig",
            name="min_date",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
