# Generated by Django 5.1.2 on 2024-12-24 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_orderconfig_max_date_orderconfig_min_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderconfig",
            name="max_date",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
