# Generated by Django 5.1.2 on 2024-12-24 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_orderconfig_max_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderconfig",
            name="max_date",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
