# Generated by Django 5.1.2 on 2024-11-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderconfig_orderconfigexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfig',
            name='weekend_disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderconfigexception',
            name='on_date',
            field=models.DateField(unique=True),
        ),
    ]
