# Generated by Django 5.1.2 on 2025-02-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_orderconfig_notification_on_statues"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default=375291234567, max_length=13),
            preserve_default=False,
        ),
    ]
